version: '2.1'

services:
    backend:
        build:
            dockerfile: docker/Server.Dockerfile
            context: .
        image: hse_ms_bot:latest
        restart: always
        env_file: .env
        expose:
            - 8000
        depends_on:
            postgres:
                condition: service_healthy

    ms:
        build:
            dockerfile: docker/MS.Dockerfile
            context: .
        image: ms:latest
        restart: always
        env_file: .env
        ports:
            - 8001:8001

    worker:
        build:
            dockerfile: docker/Worker.Dockerfile
            context: .
        image: worker:latest
        restart: always
        env_file: .env

    postgres:
        image: postgres:12.2
        restart: always
        environment:
            POSTGRES_USER: hse_ms_bot
            POSTGRES_PASSWORD: hse_ms_bot
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U hse_ms_bot"]
            interval: 10s
            timeout: 5s
            retries: 5